/* THIS FILE HAS BEEN AUTOGENERATED BY FLORA-TOOLS */

#ifndef PROTOCOL_GLORIA_GLORIA_CONSTANTS_H_
#define PROTOCOL_GLORIA_GLORIA_CONSTANTS_H_

#include <stdint.h>

#define GLORIA_HEADER_LENGTH %%GLORIA_HEADER_LENGTH%%
#define GLORIA_ACK_LENGTH %%GLORIA_ACK_LENGTH%%
#define GLORIA_CLOCK_DRIFT %%GLORIA_CLOCK_DRIFT%% // +- %%GLORIA_CLOCK_DRIFT_PLUSMINUS%% ppm @ %%TIMER_FREQUENCY%%
#define GLORIA_BLACK_BOX_SYNC_DELAY %%GLORIA_BLACK_BOX_SYNC_DELAY%% // %%human_time(GLORIA_BLACK_BOX_SYNC_DELAY)%%

typedef struct {
	uint32_t slotOverhead;
	uint32_t slotAckOverhead;
	uint32_t floodInitOverhead;
	uint32_t floodFinishOverhead;
	uint32_t rxOffset;
	uint32_t rxTriggerDelay;
	uint32_t txTriggerDelay;
	uint32_t txSync;
} gloria_timings_t;

extern gloria_timings_t gloria_timings[];

#endif /* PROTOCOL_GLORIA_GLORIA_CONSTANTS_H_ */
