/* THIS FILE HAS BEEN AUTOGENERATED BY FLORA-TOOLS */

#include "gloria_constants.h"

gloria_timings_t gloria_timings[] = {
    <%- for timing in gloria_timings %>
    { // %%loop.index-1%%
        .slotOverhead = %%timing.slot_overhead%%,
        .slotAckOverhead = %%timing.slot_ack_overhead%%,
        .floodInitOverhead = %%timing.flood_init_overhead%%,
        .floodFinishOverhead = %%timing.flood_finish_overhead%%,
        .rxOffset = %%timing.rx_offset%%,
        .rxTriggerDelay = %%timing.rx_trigger_delay%%,
        .txTriggerDelay = %%timing.tx_trigger_delay%%,
        .txSync = %%timing.tx_sync%%,
    },
    <%- endfor %>
}
